# Generated by Django 3.1.6 on 2021-02-02 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('vat', models.BooleanField()),
                ('source', models.CharField(max_length=100)),
                ('start_time', models.DateField()),
                ('granularity', models.CharField(choices=[('day', 'Daily'), ('week', 'Weekly'), ('month', 'Monthly'), ('season', 'Each quarter')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('n', 'Not provided')], max_length=1)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('late', 'Default of payment'), ('subscribed', 'Subscribed, but no payment confirmation')], max_length=15)),
                ('access', models.CharField(choices=[('premium', 'API, Dashboard and report access'), ('api', 'Only API access'), ('report', 'Only report service'), ('dashboard', 'Only dashboard access')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.DateField(max_length=5)),
                ('base_year', models.CharField(max_length=100)),
                ('granularity', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PointOfOrigin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=75)),
                ('country_acronym', models.CharField(max_length=10)),
                ('eu', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=100)),
                ('currency_acronym', models.CharField(max_length=5)),
                ('measure', models.CharField(max_length=100)),
                ('measure_acronym', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('date', models.DateField()),
                ('traded_volume', models.IntegerField()),
                ('counter_update', models.PositiveSmallIntegerField(default=0)),
                ('commodity_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.commodityproduct')),
            ],
            options={
                'ordering': ['-counter_update'],
            },
        ),
        migrations.CreateModel(
            name='IndexValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('date', models.DateField(max_length=5)),
                ('index', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.index')),
            ],
        ),
        migrations.AddField(
            model_name='index',
            name='point_of_origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.pointoforigin'),
        ),
        migrations.AddField(
            model_name='index',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.unit'),
        ),
        migrations.AddField(
            model_name='commodityproduct',
            name='point_of_origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.pointoforigin'),
        ),
        migrations.AddField(
            model_name='commodityproduct',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.unit'),
        ),
    ]
